name: Deploy

on:
 
 workflow_dispatch:
   inputs:
     resourceGroupName:
       description: 'Name of the resource group'
       default: 'rg-durable-function-demo'
       required: true
     location:
       description: 'Location where all resources will be created'
       default: 'eastus'
       required: true
     addressSpaceVnet:
       description: 'CIDR of the VNET for the Seeder VM'
       default: '10.0.0.0/16'
       required: true
     addressSpaceSubnet:
       description: 'CIDR of the Subnet for the Seeder VM'
       default: '10.0.0.0/27'
       required: true
      

jobs:
  create-azure-resources:

    runs-on: ubuntu-latest

    outputs:
      vmName: ${{ steps.armDeployment.outputs.vmName }}
      functionProcessorName: ${{ steps.armDeployment.outputs.functionProcessorName }}
      functionModelName: ${{ steps.armDeployment.outputs.functionModelName }}

    steps:

      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  

      - name: Create Resource Group
        run: |
          az group create -n ${{ github.event.inputs.resourceGroupName }} -l ${{ github.event.inputs.location }}
 
      # Temporary step the bicep linter return an error today for the
      # method PATCH for CORS on storage
      - name: Convert to ARM template
        run: |
          bicep build ./bicep/main.bicep

      - name: Deploy Azure Resources
        id: armDeployment
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ github.event.inputs.resourceGroupName }}
          template: ./bicep/main.json
          parameters: location=${{ github.event.inputs.location }} addressSpaceVnet=${{ github.event.inputs.addressSpaceVnet }} addressSpaceSubnet=${{ github.event.inputs.addressSpaceSubnet }} adminUsername=${{ secrets.ADMIN_USERNAME }} adminPassword=${{ secrets.ADMIN_PASSWORD }}

  configure-vm:

     needs: create-azure-resources

     runs-on: windows-latest

     steps:

      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Run PowerShell script
        uses: azure/powershell@v1
        with:
          azPSVersion: '3.1.0'
          inlineScript: |
            Set-AzVMCustomScriptExtension -ResourceGroupName ${{ github.event.inputs.resourceGroupName }} `
                -VMName ${{ needs.create-azure-resources.outputs.vmName }} `
                -Location ${{ github.event.inputs.location }} `
                -FileUri https://raw.githubusercontent.com/hugogirard/durableFunctionFormRecognizer/main/scripts/setup_vm.ps1 `
                -Run 'setup_vm.ps1' `
                -Name SetupVmScript

      - name: List if logfile present
        run: |
          ls

  deploy-blazor-app:

     needs: create-azure-resources

     runs-on: ubuntu-latest

     env:
        AZURE_WEBAPP_PACKAGE_PATH: './src/viewer'

     steps:

        - uses: actions/checkout@v2

        - name: Azure Login
          uses: Azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}  
            
        - name: Setup .NET Version 5
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 5.0.x
            
        - name: dotnet build and publish
          run: |
            dotnet restore
            dotnet build --configuration Release
            dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/output'

        - name: 'Run Azure webapp deploy action using publish profile credentials'
          uses: azure/webapps-deploy@v2
          with: 
            app-name: ${{ needs.create-azure-resources.outputs.webAppName }}
            package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/output' 
            
        - name: logout
          run: |
            az logout                        

  deploy-processor-function:

     needs: create-azure-resources

     runs-on: ubuntu-latest
     
     env:
       AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/processor'

     steps:

        - uses: actions/checkout@v2

        - name: Azure Login
          uses: Azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}  

        - name: Setup DotNet 3.1.X Environment
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '3.1.x'

        - name: 'Building with Dotnet'
          shell: bash
          run: |
            pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
            dotnet build --configuration Release --output ./output
            popd

        - name: 'Run Azure Functions Action'
          uses: Azure/functions-action@v1
          id: fa
          with:
            app-name: ${{ needs.create-azure-resources.outputs.functionProcessorName }}
            package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'   

        - name: logout
          run: |
            az logout                  

  deploy-model-function:
     
     needs: create-azure-resources

     runs-on: ubuntu-latest
     
     env:
       AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/TrainModel'

     steps:

        - uses: actions/checkout@v2

        - name: Azure Login
          uses: Azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}  

        - name: Setup DotNet 3.1.X Environment
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '3.1.x'

        - name: 'Building with Dotnet'
          shell: bash
          run: |
            pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
            dotnet build --configuration Release --output ./output
            popd

        - name: 'Run Azure Functions Action'
          uses: Azure/functions-action@v1
          id: fa
          with:
            app-name: ${{ needs.create-azure-resources.outputs.functionModelName }}
            package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'                     

        - name: logout
          run: |
            az logout      

