name: Deploy seeder function
on:
 push:
   branches:
     - 'main'
   paths:
     - './scr/seeder/*'
 workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'scr/seeder/'
  NODE_VERSION: '14.x'

jobs:
  create-azure-resources:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  

      - name: List Directory
        shell: bash
        run: |
          echo ls

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Resolve Project Dependencies Using Npm'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          npm run build --if-present
          npm run test --if-present
          popd

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ secrets.FUNCTION_SEEDER_NAME }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'                