name: Deploy seeder function
on:
 push:
   branches:
     - 'main'
   paths:
     - 'scr/seeder/*'
 workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'scr/seeder/'

jobs:
  create-azure-resources:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  

      - name: Setup DotNet 3.1 Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ secrets.FUNCTION_SEEDER_NAME }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'                